FROM golang
ARG PORT
ARG SERVICE
ARG DB_HOST
ARG DB_PORT
ARG DB_DATABASE
ARG DB_USERNAME
ARG DB_PASSWORD

WORKDIR .

ENV DB_HOST=${DB_HOST} DB_PORT=${DB_PORT} DB_DATABASE=${DB_DATABASE} DB_USERNAME=${DB_USERNAME} DB_PASSWORD=${DB_PASSWORD}

COPY go.mod .
RUN go mod download

EXPOSE ${PORT}

COPY private.rsa private.rsa

COPY . .

RUN go build -o app ./cmd/${SERVICE}
CMD ["./app"]


