apiVersion: v1
kind: Service
metadata:
  name: password-keeper-service
spec:
  selector:
    app: password-keeper
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer