name: CI

on:
  push:
    branches:
      - mvp
  pull_request:
    branches:
      - mvp

jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1.21

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: qwerty,
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
        ports:
          - 5444:5432

    steps:
      - name: Checkout mvp
        uses: action/checkout@2

      - name: Setup go deps
        run: |
          go install golang.org/x/tools/cmd/goimports@latest

      - name: Test
        uses: go test github.com/NikitaBarysh/password_keeper/internal/server/handler github.com/NikitaBarysh/password_keeper/internal/server/service