name: CI

on:
  push:
    branches:
      - mvp
  pull_request:
    branches:
      - mvp

jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1.20

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: qwerty
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
        ports:
          - "5444:5432"

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4

      - name: Setup Go environment
        uses: actions/setup-go@v2

      - name: Setup go deps
        run: |
          go install golang.org/x/tools/cmd/goimports@latest

      - name: Test
        run: go test ./...