name: CI

on:
  push:
    branches:
      - mvp
  pull_request:
    branches:
      - mvp

jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1.20

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: qwerty
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
        ports:
          - "5444:5432"
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4

      - name: Setup Go environment
        uses: actions/setup-go@v2

      - name: Setup go deps
        run: |
          go install golang.org/x/tools/cmd/goimports@latest

      - name: Install Migrate
        run: |
          curl -LJO https://github.com/golang-migrate/migrate/releases/download/v4.14.1/migrate.linux-amd64.tar.gz
          tar -xvf migrate.linux-amd64.tar.gz
          mv migrate.linux-amd64 /usr/local/bin/migrate
          chmod +x /usr/local/bin/migrate

      - name: Test
        run: |
          migrate -path ./schema -database 'postgres://postgres:qwerty@postgres:5432/postgres?sslmode=disable' up
          sleep 3
          go test ./...